version: "3"

services:
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile-dev
    ports:
      - 8180:8080
    volumes:
      - ./client:/data

  server:
    build: 
      context: ./server
      dockerfile: Dockerfile-dev
    ports:
      - 8181:8081
    volumes:
      - ./server:/data
    depends_on: 
      - server-database
    environment:
      - DATABASE_URL=server-database:27017
    
  server-database:
    image: mongo
    ports:
      - 27117:27017
    volumes:
      - ./db:/data/db