FROM node:carbon

COPY ./docker/entrypoint.sh /entrypoint/

RUN ["chmod", "+x", "entrypoint/entrypoint.sh"]

RUN echo "server/Dockerfile-dev"

# Copy or mount node app here
WORKDIR /data/

EXPOSE 8181

ENTRYPOINT ["/entrypoint/entrypoint.sh"]

CMD ["npm", "start"]

